### ISSUE TITLE
Direct message to bot

### ISSUE THREAD

**Issue by anojansivarajah** [outofcoffee/corebot#12]
It would be nice to be able to message the bot directly. This means a channel doesn't get loads of messages and when a user types command he/she doesn't need to address the bot as it is a direct message. I had a look and its a simple change, so if @pcornish @outofcoffee another pull request https://github.com/outofcoffee/corebot/pull/13

Cheers

**Comment by anojansivarajah** [comment]
Hello, Any thoughts on this @outofcoffee @pcornish ?

**Comment by outofcoffee** [comment]
Hi @anojansivarajah, thanks for the feature suggestion. This was something we've been thinking about but hadn't gotten around to.

There are some considerations in introducing this feature.

1. Whilst I appreciate this is an option, rather than a change per se, I would welcome your thoughts on whether moving the deployment conversations out of a shared channel is bad for visibility and somewhat counter to the benefits of the ChatOps philosophy. Part of the strength of having it all in one place is so that discussion, decision and action all happen in a single space, thereby ensuring folks have a good shared understanding. Going direct to the bot is less helpful in this regard, but I can see how it might fit some use cases. Should we have an option to disable direct communication unless explicitly enabled?

2. Given the inherently more private nature of a one-to-one discussion, should we open up more config options when talking to the bot directly? For example, could the user set preferences specific to them by talking to the bot directly?

**Comment by anojansivarajah** [comment]
@outofcoffee Only reason i wanted private chat is to reduce clutter in the channel. I understand your concern. I too think that it defeats the ChatOps philosophy. So I will close this pull request. Once https://github.com/Ullink/simple-slack-api/pull/177 gets merged and released, we can create the reply in thread feature which will achieve what i wanted.

Thanks
